name: Build QEMU
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup toolchain
      run:
        ./scripts/make-cross-compilers.sh
        gmake TARGET=qemu bin
